In [2]:
import json
import pandas as pd

df = pd.read_csv('./data.csv')

In [3]:
df

,itemid,shopid,userid,price_max_before_discount,has_lowest_price_guarantee,price_before_discount,price_min_before_discount,exclusive_price_info,hidden_price_display,price_min,...,flash_sale,upcoming_flash_sale,deep_discount,has_low_fulfillment_rate,is_partial_fulfilled,makeups,shop_vouchers,global_sold,is_infant_milk_formula_product,topic
0,1417823595,48865237,0,900000000,False,500000000,500000000,NaN,NaN,300000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
1,10958521551,101281841,0,-1,False,0,-1,NaN,NaN,6800000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
2,11848818786,466736605,0,-1,False,0,-1,NaN,NaN,290000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
3,7453772621,63082962,0,-1,False,0,-1,NaN,NaN,19900000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
4,2316916236,109787200,0,-1,False,0,-1,NaN,NaN,1100000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8033,4834669559,263481983,0,-1,False,0,-1,NaN,NaN,7500000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
8034,720677722,10931069,0,-1,False,0,-1,NaN,NaN,3000000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
8035,1784828154,39317517,0,-1,False,0,-1,NaN,NaN,7200000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
8036,4732390034,33931138,0,22000000000,False,12000000000,12000000000,NaN,NaN,6000000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971
8037,6249913180,303263608,0,41500000000,False,41500000000,41500000000,NaN,NaN,26900000000,...,NaN,NaN,NaN,False,False,NaN,NaN,NaN,False,11036971